version: '3.8'
services:
  assistente-api:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: desafio-solutis
    env_file:
      - ./.env.sample
    ports:
      - '5000:5000'
    expose:
      - '5000'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - desafio-solutis
  db:
    image: postgres:10.20-alpine
    restart: always
    environment:
      POSTGRES_DB: desafio-solutis
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./docker-postgres-init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    container_name: db-desafiosolutis
    ports:
      - '5432:5432'
    expose:
      - '5432'
    networks:
      - desafio-solutis
    healthcheck:
      interval: 5s
      timeout: 5s
      retries: 5


